name: 'jira-ticket-actions'
description: 'Create or Update a Jira release and modify version on related tickets.'
author: 'Vicente Albert'
inputs:
  email:
    required: true
    description: Email address associated with api token
  api_token:
    required: true
    description: Jira API token
  subdomain:
    required: true
    description: '{subdomain}.atlassian.net'
  jira_project:
    required: true
    description: 'Id of the JIRA project'
  release_name:
    required: true
    description: Name of the release
  release_prefix:
    required: true
    description: Prefix for release
  gh_user:
    required: true
    description: Github user
  gh_token:
    required: true
    description: Github token
  gh_repository:
    required: true
    description: Github repository
  slack_token:
    required: false
    description: Slack oauth token
  slack_channel:
    required: false
    description: Slack channelId
  slack_environment:
    required: false
    description: Environment to post slack message
  dry_run:
    description: Dump the config
    required: false
    default: 'false'

branding:
  icon: 'package'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/index.js'
